In [1]:
import numpy as np
import pandas as pd


In [2]:
promotional = pd.read_csv('dataset/promotional_expense.csv')
holidays = pd.read_csv('dataset/holidays.csv')
test = pd.read_csv('dataset/yds_test2018.csv')

In [3]:
from pandas import datetime
from pandas import DataFrame
from statsmodels.tsa.arima_model import ARIMA
from matplotlib import pyplot
from pandas.tools.plotting import autocorrelation_plot

In [4]:
train = pd.read_csv('train.csv',parse_dates=[0], header=0,date_parser=parser,index_col=0).Sales

NameError: name 'parser' is not defined

In [ ]:
train.head()

In [5]:
train_1_a = pd.read_csv('train/train_1_a.csv',parse_dates=[1],header=0,index_col=1).Sales
train_1_a.head()

Date
2013-01-01    157500.0
2013-01-01     39375.0
2013-01-01     15750.0
2013-01-01     47250.0
2013-01-01    283500.0
Name: Sales, dtype: float64

In [6]:
train_1_a = pd.read_csv('train/train_1_a.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_a = pd.read_csv('train/train_2_a.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_a = pd.read_csv('train/train_3_a.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_a = pd.read_csv('train/train_4_a.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_a = pd.read_csv('train/train_5_a.csv',parse_dates=[1], header=0,index_col=1).Sales

train_1_b = pd.read_csv('train/train_1_b.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_b = pd.read_csv('train/train_2_b.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_b = pd.read_csv('train/train_3_b.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_b = pd.read_csv('train/train_4_b.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_b = pd.read_csv('train/train_5_b.csv',parse_dates=[1], header=0,index_col=1).Sales

train_1_c = pd.read_csv('train/train_1_c.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_c = pd.read_csv('train/train_2_c.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_c = pd.read_csv('train/train_3_c.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_c = pd.read_csv('train/train_4_c.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_c = pd.read_csv('train/train_5_c.csv',parse_dates=[1], header=0,index_col=1).Sales

train_1_d = pd.read_csv('train/train_1_d.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_d = pd.read_csv('train/train_2_d.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_d = pd.read_csv('train/train_3_d.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_d = pd.read_csv('train/train_4_d.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_d = pd.read_csv('train/train_5_d.csv',parse_dates=[1], header=0,index_col=1).Sales

train_1_e = pd.read_csv('train/train_1_e.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_e = pd.read_csv('train/train_2_e.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_e = pd.read_csv('train/train_3_e.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_e = pd.read_csv('train/train_4_e.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_e = pd.read_csv('train/train_5_e.csv',parse_dates=[1], header=0,index_col=1).Sales

train_1_f = pd.read_csv('train/train_1_f.csv',parse_dates=[1], header=0,index_col=1).Sales
train_2_f = pd.read_csv('train/train_2_f.csv',parse_dates=[1], header=0,index_col=1).Sales
train_3_f = pd.read_csv('train/train_3_f.csv',parse_dates=[1], header=0,index_col=1).Sales
train_4_f = pd.read_csv('train/train_4_f.csv',parse_dates=[1], header=0,index_col=1).Sales
train_5_f = pd.read_csv('train/train_5_f.csv',parse_dates=[1], header=0,index_col=1).Sales

In [122]:
# train_4_e

In [76]:
# train_1_a = train[train.Product_ID == 1][train.Country == 0].Sales
# train_2_a = train[train.Product_ID == 2][train.Country == 0].Sales
# train_3_a = train[train.Product_ID == 3][train.Country == 0].Sales
# train_4_a = train[train.Product_ID == 4][train.Country == 0].Sales
# train_5_a = train[train.Product_ID == 5][train.Country == 0].Sales

# train_1_b = train[train.Product_ID == 1][train.Country == 1].Sales
# train_2_b = train[train.Product_ID == 2][train.Country == 1].Sales
# train_3_b = train[train.Product_ID == 3][train.Country == 1].Sales
# train_4_b = train[train.Product_ID == 4][train.Country == 1].Sales
# train_5_b = train[train.Product_ID == 5][train.Country == 1].Sales

# train_1_c = train[train.Product_ID == 1][train.Country == 2].Sales
# train_2_c = train[train.Product_ID == 2][train.Country == 2].Sales
# train_3_c = train[train.Product_ID == 3][train.Country == 2].Sales
# train_4_c = train[train.Product_ID == 4][train.Country == 2].Sales
# train_5_c = train[train.Product_ID == 5][train.Country == 2].Sales

# train_1_d = train[train.Product_ID == 1][train.Country == 3].Sales
# train_2_d = train[train.Product_ID == 2][train.Country == 3].Sales
# train_3_d = train[train.Product_ID == 3][train.Country == 3].Sales
# train_4_d = train[train.Product_ID == 4][train.Country == 3].Sales
# train_5_d = train[train.Product_ID == 5][train.Country == 3].Sales

# train_1_e = train[train.Product_ID == 1][train.Country == 4].Sales
# train_2_e = train[train.Product_ID == 2][train.Country == 4].Sales
# train_3_e = train[train.Product_ID == 3][train.Country == 4].Sales
# train_4_e = train[train.Product_ID == 4][train.Country == 4].Sales
# train_5_e = train[train.Product_ID == 5][train.Country == 4].Sales

# train_1_f = train[train.Product_ID == 1][train.Country == 5].Sales
# train_2_f = train[train.Product_ID == 2][train.Country == 5].Sales
# train_3_f = train[train.Product_ID == 3][train.Country == 5].Sales
# train_4_f = train[train.Product_ID == 4][train.Country == 5].Sales
# train_5_f = train[train.Product_ID == 5][train.Country == 5].Sales

In [125]:
# model_1_b = ARIMA(train_1_b, order=(5,1,0))
# fit_1_b = model_1_b.fit(disp=0)
# model_2_b = ARIMA(train_2_b, order=(5,1,0))
# fit_2_b = model_2_b.fit(disp=0)
# model_3_b = ARIMA(train_3_b, order=(5,1,0))
# fit_3_b = model_3_b.fit(disp=0)
# model_4_b = ARIMA(train_4_b, order=(5,1,0))
# fit_4_b = model_4_b.fit(disp=0)
# model_5_b = ARIMA(train_5_b, order=(5,1,0))
# fit_5_b = model_5_b.fit(disp=0)

In [7]:
model_1_a = ARIMA(train_1_a, order=(5,1,0))
fit_1_a = model_1_a.fit(disp=0)
model_2_a = ARIMA(train_2_a, order=(5,1,0))
fit_2_a = model_2_a.fit(disp=0)
model_3_a = ARIMA(train_3_a, order=(5,1,0))
fit_3_a = model_3_a.fit(disp=0)
# model_4_a = ARIMA(train_4_a, order=(5,1,0))
# fit_4_a = model_4_a.fit(disp=0)
# model_5_a = ARIMA(train_5_a, order=(5,1,0))
# fit_5_a = model_5_a.fit(disp=0)

# model_1_b = ARIMA(train_1_b, order=(5,1,0))
# fit_1_b = model_1_b.fit(disp=0)
model_2_b = ARIMA(train_2_b, order=(5,1,0))
fit_2_b = model_2_b.fit(disp=0)
# model_3_b = ARIMA(train_3_b, order=(5,1,0))
# fit_3_b = model_3_b.fit(disp=0)
# model_4_b = ARIMA(train_4_b, order=(5,1,0))
# fit_4_b = model_4_b.fit(disp=0)
# model_5_b = ARIMA(train_5_b, order=(5,1,0))
# fit_5_b = model_5_b.fit(disp=0)

model_1_c = ARIMA(train_1_c, order=(5,1,0))
fit_1_c = model_1_c.fit(disp=0)
model_2_c = ARIMA(train_2_c, order=(5,1,0))
fit_2_c = model_2_c.fit(disp=0)
model_3_c = ARIMA(train_3_c, order=(5,1,0))
fit_3_c = model_3_c.fit(disp=0)
# model_4_c = ARIMA(train_4_c, order=(5,1,0))
# fit_4_c = model_4_c.fit(disp=0)
# model_5_c = ARIMA(train_5_c, order=(5,1,0))
# fit_5_c = model_5_c.fit(disp=0)

# model_1_d = ARIMA(train_1_d, order=(5,1,0))
# fit_1_d = model_1_d.fit(disp=0)
model_2_d = ARIMA(train_2_d, order=(5,1,0))
fit_2_d = model_2_d.fit(disp=0)
# model_3_d = ARIMA(train_3_d, order=(5,1,0))
# fit_3_d = model_3_d.fit(disp=0)
# model_4_d = ARIMA(train_4_d, order=(5,1,0))
# fit_4_d = model_4_d.fit(disp=0)
# model_5_d = ARIMA(train_5_d, order=(5,1,0))
# fit_5_d = model_5_d.fit(disp=0)





/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it h

In [8]:
# model_1_e = ARIMA(train_1_e, order=(5,1,0))
# fit_1_e = model_1_e.fit(disp=0)
# model_2_e = ARIMA(train_2_e, order=(5,1,0))
# fit_2_e = model_2_e.fit(disp=0)
# model_3_e = ARIMA(train_3_e, order=(5,1,0))
# fit_3_e = model_3_e.fit(disp=0)
model_4_e = ARIMA(train_4_e, order=(5,1,0))
fit_4_e = model_4_e.fit(disp=0)
model_5_e = ARIMA(train_5_e, order=(5,1,0))
fit_5_e = model_5_e.fit(disp=0)

# model_1_f = ARIMA(train_1_f, order=(5,1,0))
# fit_1_f = model_1_f.fit(disp=0)
# model_2_f = ARIMA(train_2_f, order=(5,1,0))
# fit_2_f = model_2_f.fit(disp=0)
# model_3_f = ARIMA(train_3_f, order=(5,1,0))
# fit_3_f = model_3_f.fit(disp=0)
model_4_f = ARIMA(train_4_f, order=(5,1,0))
fit_4_f = model_4_f.fit(disp=0)
# model_5_f = ARIMA(train_5_f, order=(5,1,0))
# fit_5_f = model_5_f.fit(disp=0)

/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it h

In [66]:
# def parser(x):
#     return datetime.strptime(x, '%Y-%m')

In [9]:
test.drop(columns = ['Sales'],inplace = True)

In [10]:
test.head()

S_No  Year  Month  Product_ID    Country
0  79073  2016      4           1  Argentina
1  79074  2016      5           1  Argentina
2  79075  2016      6           1  Argentina
3  79076  2016      7           1  Argentina
4  79077  2016      8           1  Argentina

In [11]:
map_array = {
    'Argentina': 0,
    'Belgium':1,
    'Columbia':2,
    'Denmark':3,
    'England':4,
    'Finland':5
}

In [12]:
test.Country = test.Country.map(map_array)

In [13]:
test.head()

S_No  Year  Month  Product_ID  Country
0  79073  2016      4           1        0
1  79074  2016      5           1        0
2  79075  2016      6           1        0
3  79076  2016      7           1        0
4  79077  2016      8           1        0

In [183]:
len(test_1_a ) + len(test_2_a) + len(test_3_a) + len(test_2_b) + len(test_1_c) + len(test_2_c) + len(test_3_c) + len(test_2_d) + len(test_4_e) + len(test_5_e) + len(test_4_f)

105

In [16]:
history_1_a = [x for x in train_1_a]
predictions_1_a = []
for t in range(len(test_1_a)):
    model= ARIMA(history_1_a, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_1_a.append(yhat)
#     obs = test_1_a.iloc[t]
    history_1_a.append(yhat)
predictions_1_a

[array([108541.1924]),
 array([110119.62939173]),
 array([131972.03541719]),
 array([128543.21382873]),
 array([115140.77135503]),
 array([134576.92703985]),
 array([122209.96823544]),
 array([123502.82598136]),
 array([126102.82957381]),
 array([124827.86482637]),
 array([124319.53982138]),
 array([125929.29096828])]

In [17]:
history_2_a = [x for x in train_2_a]
predictions_2_a = []
for t in range(len(test_2_a)):
    model= ARIMA(history_2_a, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_2_a.append(yhat)
#     obs = test_1_a.iloc[t]
    history_2_a.append(yhat)
predictions_2_a

/home/sidkathuria14/.local/lib/python3.5/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


[array([11934.96829563]),
 array([13205.95186924]),
 array([10891.40707656]),
 array([14439.19233737]),
 array([11337.49763839]),
 array([12118.16770118]),
 array([12269.49969371]),
 array([12396.8607567]),
 array([12065.86407596]),
 array([12408.20626693]),
 array([12122.63066827]),
 array([12173.66795873])]

In [18]:
history_3_a = [x for x in train_3_a]
predictions_3_a = []
for t in range(len(test_3_a)):
    model= ARIMA(history_3_a, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_3_a.append(yhat)
#     obs = test_1_a.iloc[t]
    history_3_a.append(yhat)
predictions_3_a

[array([665220.07489748]), array([510939.8341125]), array([684740.42840349])]

In [19]:
history_2_b = [x for x in train_2_b]
predictions_2_b = []
for t in range(len(test_2_b)):
    model= ARIMA(history_2_b, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_2_b.append(yhat)
#     obs = test_1_a.iloc[t]
    history_2_b.append(yhat)
predictions_2_b

[array([39039.45877867]),
 array([15250.00825399]),
 array([16595.48656186]),
 array([17947.70714377]),
 array([16402.33386328]),
 array([18930.50168055]),
 array([20611.99426702]),
 array([17544.43051079]),
 array([18092.63101235]),
 array([18288.08420979]),
 array([18321.94995171]),
 array([18695.92914849])]

In [20]:
history_1_c = [x for x in train_1_c]
predictions_1_c = []
for t in range(len(test_1_c)):
    model= ARIMA(history_1_c, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_1_c.append(yhat)
#     obs = test_1_a.iloc[t]
    history_1_c.append(yhat)
predictions_1_c

[array([1714.13445948]),
 array([966.87201817]),
 array([1081.81680991]),
 array([1233.5445708]),
 array([1080.05507127]),
 array([1135.79281839]),
 array([1191.00655498]),
 array([1121.379052]),
 array([1140.96612269]),
 array([1148.29628132]),
 array([1135.45234299]),
 array([1144.03315164])]

In [21]:
history_2_c = [x for x in train_2_c]
predictions_2_c = []
for t in range(len(test_2_c)):
    model= ARIMA(history_1_a, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_2_c.append(yhat)
#     obs = test_1_a.iloc[t]
    history_2_c.append(yhat)
predictions_2_c

[array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367]),
 array([124532.51835367])]

In [22]:
history_3_c = [x for x in train_3_c]
predictions_3_c = []
for t in range(len(test_3_c)):
    model= ARIMA(history_3_c, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_3_c.append(yhat)
#     obs = test_1_a.iloc[t]
    history_3_c.append(yhat)
predictions_3_c

[array([240.78515601]), array([74.0683601]), array([62.93179624])]

In [23]:
history_2_d = [x for x in train_2_d]
predictions_2_d = []
for t in range(len(test_2_d)):
    model= ARIMA(history_2_d, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_2_d.append(yhat)
#     obs = test_1_a.iloc[t]
    history_2_d.append(yhat)
predictions_2_d

[array([2980.25347315]),
 array([3323.52908701]),
 array([3791.15301887]),
 array([4629.77890514]),
 array([5502.25867406]),
 array([2964.18767375]),
 array([3549.24576186]),
 array([3623.40134664]),
 array([3681.8401579]),
 array([3691.57559855]),
 array([3527.99046699]),
 array([3172.66110864])]

In [24]:
history_4_e = [x for x in train_4_e]
predictions_4_e = []
for t in range(len(test_4_e)):
    model= ARIMA(history_4_e, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_4_e.append(yhat)
#     obs = test_1_a.iloc[t]
    history_4_e.append(yhat)
predictions_4_e

[array([1670.10623397]),
 array([2251.45152896]),
 array([1998.9258402]),
 array([2621.44388588]),
 array([1535.92780997]),
 array([1766.88179647]),
 array([1945.78423519]),
 array([2037.50281861]),
 array([1946.38724008])]

In [25]:
history_5_e = [x for x in train_5_e]
predictions_5_e = []
for t in range(len(test_5_e)):
    model= ARIMA(history_5_e, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_5_e.append(yhat)
#     obs = test_1_a.iloc[t]
    history_5_e.append(yhat)
predictions_5_e

[array([5914.77533536]),
 array([6501.3760186]),
 array([2167.26854503]),
 array([2615.26099015]),
 array([3128.01752634]),
 array([3502.32598131]),
 array([3950.63714086]),
 array([3598.60057339]),
 array([3143.39490963])]

In [26]:
history_4_f = [x for x in train_4_f]
predictions_4_f = []
for t in range(len(test_4_f)):
    model= ARIMA(history_4_f, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions_4_f.append(yhat)
#     obs = test_1_a.iloc[t]
    history_4_f.append(yhat)
predictions_4_f

[array([9942.81148622]),
 array([3720.75824049]),
 array([2545.37862562]),
 array([1851.54231926]),
 array([2397.83428353]),
 array([2990.05133371]),
 array([4538.55663242]),
 array([3277.88655762]),
 array([2938.77282842])]

In [ ]:
# test.drop(columns = ['Sales'])

In [15]:
test_1_a = test[test.Country == 0][test.Product_ID == 1]
test_2_a = test[test.Country == 0][test.Product_ID == 2]
test_3_a = test[test.Country == 0][test.Product_ID == 3]

test_2_b = test[test.Country == 1][test.Product_ID == 2]

test_1_c = test[test.Country == 2][test.Product_ID == 1]
test_2_c = test[test.Country == 2][test.Product_ID == 2]
test_3_c = test[test.Country == 2][test.Product_ID == 3]

test_2_d = test[test.Country == 3][test.Product_ID == 2]

test_4_e = test[test.Country == 4][test.Product_ID == 4]
test_5_e = test[test.Country == 4][test.Product_ID == 5]

test_4_f = test[test.Country == 5][test.Product_ID == 4]

/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.
/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  
/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """
/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys
/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_l

In [181]:
len(y_1_a) + len(y_2_a) + len(y_3_a) + len(y_1_c) + len(y_2_b) + len(y_2_c) + len(y_3_c) + len(y_2_d) + len(y_4_e) + len(y_5_e) + len(y_4_f)

33

In [27]:
test['Sales'] = np.zeros(105)

In [28]:
test.head()

S_No  Year  Month  Product_ID  Country  Sales
0  79073  2016      4           1        0    0.0
1  79074  2016      5           1        0    0.0
2  79075  2016      6           1        0    0.0
3  79076  2016      7           1        0    0.0
4  79077  2016      8           1        0    0.0

In [29]:
# for i in range(len(predictions_1_a)):
#     test[test.Country == 0][test.Product_ID == 1].Sales.iloc[i] = predictions_1_a[i]

In [30]:
predictions_1_a

[array([108541.1924]),
 array([110119.62939173]),
 array([131972.03541719]),
 array([128543.21382873]),
 array([115140.77135503]),
 array([134576.92703985]),
 array([122209.96823544]),
 array([123502.82598136]),
 array([126102.82957381]),
 array([124827.86482637]),
 array([124319.53982138]),
 array([125929.29096828])]

In [224]:
test[test.Country == 0][test.Product_ID == 1]

/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


Year  Month  Product_ID  Country  Sales
0   2016      4           1        0    0.0
1   2016      5           1        0    0.0
2   2016      6           1        0    0.0
3   2016      7           1        0    0.0
4   2016      8           1        0    0.0
5   2016      9           1        0    0.0
6   2016     10           1        0    0.0
7   2016     11           1        0    0.0
8   2016     12           1        0    0.0
9   2017      1           1        0    0.0
10  2017      2           1        0    0.0
11  2017      3           1        0    0.0

In [228]:
test_1_a

Year  Month  Product_ID  Country
0   2016      4           1        0
1   2016      5           1        0
2   2016      6           1        0
3   2016      7           1        0
4   2016      8           1        0
5   2016      9           1        0
6   2016     10           1        0
7   2016     11           1        0
8   2016     12           1        0
9   2017      1           1        0
10  2017      2           1        0
11  2017      3           1        0

In [233]:
test.head()

Year  Month  Product_ID  Country  Sales
0  2016      4           1        0    0.0
1  2016      5           1        0    0.0
2  2016      6           1        0    0.0
3  2016      7           1        0    0.0
4  2016      8           1        0    0.0

In [68]:
rev_map = {
    0:'Argentina',
    1:'Belgium',
    2:'Columbia',
    3:'Denmark',
    4:'England',
    5:'Finland'
}

In [236]:
test.Country = test.Country.map(rev_map)

In [237]:
test.head()

Year  Month  Product_ID    Country  Sales
0  2016      4           1  Argentina    0.0
1  2016      5           1  Argentina    0.0
2  2016      6           1  Argentina    0.0
3  2016      7           1  Argentina    0.0
4  2016      8           1  Argentina    0.0

In [42]:
# for i in range(105):
#     if test.Country == 'Argentina':
#         if test.Product_ID == 1:
#             test.iloc[i,4] = predictions_1_a

# test_1_a = test[test.Country == 0][test.Product_ID == 1]
# test_2_a = test[test.Country == 0][test.Product_ID == 2]
# test_3_a = test[test.Country == 0][test.Product_ID == 3]

# test_2_b = test[test.Country == 1][test.Product_ID == 2]

# test_1_c = test[test.Country == 2][test.Product_ID == 1]
# test_2_c = test[test.Country == 2][test.Product_ID == 2]
# test_3_c = test[test.Country == 2][test.Product_ID == 3]

# test_2_d = test[test.Country == 3][test.Product_ID == 2]

# test_4_e = test[test.Country == 4][test.Product_ID == 4]
# test_5_e = test[test.Country == 4][test.Product_ID == 5]

# test_4_f = test[test.Country == 5][test.Product_ID == 4]
test_2_a
predictions_2_a
pd.concat([test_2_a.reset_index(drop=True),DataFrame(predictions_2_a,columns = ['Sales']).reset_index(drop=True) ], ignore_index=True , axis = 1)

0     1   2  3  4             5
0   79085  2016   4  2  0  11934.968296
1   79086  2016   5  2  0  13205.951869
2   79087  2016   6  2  0  10891.407077
3   79088  2016   7  2  0  14439.192337
4   79089  2016   8  2  0  11337.497638
5   79090  2016   9  2  0  12118.167701
6   79091  2016  10  2  0  12269.499694
7   79092  2016  11  2  0  12396.860757
8   79093  2016  12  2  0  12065.864076
9   79094  2017   1  2  0  12408.206267
10  79095  2017   2  2  0  12122.630668
11  79096  2017   3  2  0  12173.667959

In [43]:
result_1_a = pd.concat([test_1_a.reset_index(drop=True), pd.DataFrame(predictions_1_a,columns = ['Sales']).reset_index(drop=True)], axis=1)
result_2_a = pd.concat([test_2_a.reset_index(drop=True), pd.DataFrame(predictions_2_a,columns = ['Sales'])], axis=1)
result_3_a = pd.concat([test_3_a.reset_index(drop=True), pd.DataFrame(predictions_3_a,columns = ['Sales'])], axis=1)

result_2_b = pd.concat([test_2_b.reset_index(drop=True), pd.DataFrame(predictions_2_b,columns = ['Sales']).reset_index(drop=True)], axis=1)

result_1_c = pd.concat([test_1_c.reset_index(drop=True), pd.DataFrame(predictions_1_c,columns = ['Sales']).reset_index(drop=True)], axis=1)
result_2_c = pd.concat([test_2_c.reset_index(drop=True), pd.DataFrame(predictions_2_c,columns = ['Sales']).reset_index(drop=True)], axis=1)
result_3_c = pd.concat([test_3_c.reset_index(drop=True), pd.DataFrame(predictions_3_c,columns = ['Sales']).reset_index(drop=True)], axis=1)

result_2_d = pd.concat([test_2_d.reset_index(drop=True), pd.DataFrame(predictions_2_d,columns = ['Sales']).reset_index(drop=True)], axis=1)

result_4_e = pd.concat([test_4_e.reset_index(drop=True), pd.DataFrame(predictions_4_e,columns = ['Sales']).reset_index(drop=True)], axis=1)
result_5_e = pd.concat([test_5_e.reset_index(drop=True), pd.DataFrame(predictions_5_e,columns = ['Sales']).reset_index(drop=True)], axis=1)

result_4_f = pd.concat([test_4_f.reset_index(drop=True), pd.DataFrame(predictions_4_f,columns = ['Sales']).reset_index(drop=True)], axis=1)

In [44]:
final = pd.concat([result_1_a,result_2_a,result_3_a,result_2_b,result_1_c,result_2_c,result_3_c,result_2_d,result_4_e,result_5_e,result_4_f],axis = 0)

In [256]:
# final.dropna(axis = 0)
# final.describe()

In [51]:
final = final.reset_index()

In [47]:
# result_2_a

In [52]:
final.head()

index   S_No  Year  Month  Product_ID  Country          Sales
0      0  79073  2016      4           1        0  108541.192400
1      1  79074  2016      5           1        0  110119.629392
2      2  79075  2016      6           1        0  131972.035417
3      3  79076  2016      7           1        0  128543.213829
4      4  79077  2016      8           1        0  115140.771355

In [61]:
final.sort_values(by = [1],axis = 1,inplace = True)

In [66]:
# final.to_csv('final.csv')

In [62]:
test2 = pd.read_csv('dataset/yds_test2018.csv')

In [65]:
# final.subtract(test2)

In [70]:
final.Country = final.Country.map(rev_map)

In [71]:
cols = final.columns.tolist()
cols

['Country', 'index', 'Product_ID', 'Month', 'Year', 'S_No', 'Sales']

In [72]:
sample = pd.read_csv('dataset/sample_submission.csv')
sample.head()

S_No  Year  Month  Product_ID    Country  Sales
0  79073  2016      4           1  Argentina    NaN
1  79074  2016      5           1  Argentina    NaN
2  79075  2016      6           1  Argentina    NaN
3  79076  2016      7           1  Argentina    NaN
4  79077  2016      8           1  Argentina    NaN

In [73]:
new_cols = ['S_No','Year','Month','Product_ID','Country','Sales']
final = final[new_cols]

In [75]:
final.to_csv('final.csv')